### ISSUE TITLE
Having issue while launching pipeline using sdk

### ISSUE THREAD

**Issue by mamus7rout** [streamsets/tutorials#141]
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/streamsets/sdk/sdc.py", line 83, in __init__
    if self.control_hub.use_websocket_tunneling:
AttributeError: 'NoneType' object has no attribute 'use_websocket_tunneling'

**Comment by mamus7rout** [comment]
Getting error for activation key and its not present in. my installed directory.

Kindly suggest how to get the key.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bikramrout/Library/Python/3.9/lib/python/site-packages/streamsets/sdk/sdc.py", line 94, in __init__
    self.api_client = sdc_api.ApiClient(server_url=self.server_url,
  File "streamsets/sdk/sdc_api.pyx", line 139, in sdk.sdc_api.ApiClient.__init__
  File "streamsets/sdk/sdc_api.pyx", line 148, in sdk.sdc_api.ApiClient._verify_activation
streamsets.sdk.exceptions.ActivationError: Failed to activate Python SDK for StreamSets (reason: Could not find activation file at /Users/bikramrout/.streamsets/activation/rsa-signed-activation-info.properties or /Users/bikramrout/Library/Python/3.9/lib/python/site-packages/streamsets/sdk/activation/rsa-signed-activation-info.properties or environment variable STREAMSETS_SDK_ACTIVATION_KEY).
