### ISSUE TITLE
Error in SDK for python

### ISSUE THREAD

**Issue by mamus7rout** [streamsets/tutorials#142]
from streamsets.sdk import DataCollector
DataCollector.VERIFY_SSL_CERTIFICATES = False
sdc = DataCollector('https://na01.hub.streamsets.com')

I tried with above code snippet to connect to my data collector but i am getting error as given below.

"/usr/local/bin/python3 /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/s
treamsets/sdk/test.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/streamsets/sdk/test.py", line 3, in <module>
    sdc = DataCollector('https://na01.hub.streamsets.com')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/streamsets/sdk/sdc.py", line 83, in __init__
    if self.control_hub.use_websocket_tunneling:
AttributeError: 'NoneType' object has no attribute 'use_websocket_tunneling'

"

May i know how to get the DataCollector.VERIFY_SSL_CERTIFICATES  in my system , i was referring the documents but it didn't help me .

 
During SDK activation , when i am running the below script , i am also getting error.

bikramrout@Bikrams-MacBook-Air ~ % pip3 install streamsets~=3.0                                        
Collecting streamsets~=3.0
  Using cached streamsets-3.12.1.tar.gz (3.7 MB)
  Preparing metadata (setup.py) ... done
Collecting dpath==1.4.2
  Using cached dpath-1.4.2.tar.gz (14 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/kv/z10gtcs561n998_5h4sbh1sc0000gn/T/pip-install-adp2hj2t/dpath_4aa343ff9c4b4e80a2085baae78d4486/setup.py", line 2, in <module>
          import dpath.version
        File "/private/var/folders/kv/z10gtcs561n998_5h4sbh1sc0000gn/T/pip-install-adp2hj2t/dpath_4aa343ff9c4b4e80a2085baae78d4486/dpath/__init__.py", line 13, in <module>
          from .util import *
        File "/private/var/folders/kv/z10gtcs561n998_5h4sbh1sc0000gn/T/pip-install-adp2hj2t/dpath_4aa343ff9c4b4e80a2085baae78d4486/dpath/util.py", line 1, in <module>
          import dpath.path
        File "/private/var/folders/kv/z10gtcs561n998_5h4sbh1sc0000gn/T/pip-install-adp2hj2t/dpath_4aa343ff9c4b4e80a2085baae78d4486/dpath/path.py", line 9, in <module>
          from collections import MutableSequence, MutableMapping
      ImportError: cannot import name 'MutableSequence' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by mamus7rout** [comment]
Managed to fix the issue ,so closing the issue.
