### ISSUE TITLE
tutorials-1:java.lang.RuntimeException: error while performing request

### ISSUE THREAD

**Issue by sjq597** [streamsets/tutorials#44]
`2017-03-02 11:28:36,736 [user:*admin] [pipeline:tutorial01/3a5c571e-2d7a-49ce-aa5f-61006e68ea72] [thread:preview-pool-1-thread-1] WARN  Pipeline - Stage 'com_streamsets_pipeline_stage_origin_spooldir_SpoolDirDSource_1' initialization error: java.lang.RuntimeException: error while performing request
java.lang.RuntimeException: error while performing request
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:638)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:184)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:146)
	at com.streamsets.pipeline.stage.destination.elasticsearch.ElasticSearchTarget.init(ElasticSearchTarget.java:290)
	at com.streamsets.pipeline.api.base.BaseStage.init(BaseStage.java:52)
	at com.streamsets.pipeline.configurablestage.DStage.init(DStage.java:40)
	at com.streamsets.datacollector.runner.StageRuntime.init(StageRuntime.java:156)
	at com.streamsets.datacollector.runner.StagePipe.init(StagePipe.java:105)
	at com.streamsets.datacollector.runner.StagePipe.init(StagePipe.java:53)
	at com.streamsets.datacollector.runner.Pipeline.initPipe(Pipeline.java:260)
	at com.streamsets.datacollector.runner.Pipeline.init(Pipeline.java:252)
	at com.streamsets.datacollector.runner.Pipeline.validateConfigs(Pipeline.java:171)
	at com.streamsets.datacollector.runner.preview.PreviewPipeline.validateConfigs(PreviewPipeline.java:63)
	at com.streamsets.datacollector.execution.preview.sync.SyncPreviewer.validateConfigs(SyncPreviewer.java:122)
	at com.streamsets.datacollector.execution.preview.async.AsyncPreviewer$1.call(AsyncPreviewer.java:76)
	at com.streamsets.pipeline.lib.executor.SafeScheduledExecutorService$SafeCallable.call(SafeScheduledExecutorService.java:233)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.ProtocolException: Not a valid protocol version: This is not a HTTP port
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:209)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:245)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	... 1 more
Caused by: org.apache.http.ParseException: Not a valid protocol version: This is not a HTTP port
	at org.apache.http.message.BasicLineParser.parseProtocolVersion(BasicLineParser.java:148)
	at org.apache.http.message.BasicLineParser.parseStatusLine(BasicLineParser.java:366)
	at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:112)
	at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:50)
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parseHeadLine(AbstractMessageParser.java:156)
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:207)
	... 11 more
2017-03-02 11:28:37,749 [user:admin] [pipeline:tutorial01/3a5c571e-2d7a-49ce-aa5f-61006e68ea72] [thread:webserver-21] WARN  StandaloneAndClusterPipelineManager - Evicting idle previewer '3a5c571e-2d7a-49ce-aa5f-61006e68ea72::null'::'61816234-927e-4ac1-bc87-8572d47fdf97' in status 'INVALID'
`

**Comment by sjq597** [comment]
JDK:1.8.0.77
ElasticSearch: 2.3.2

**Comment by metadaddy** [comment]
`org.apache.http.ParseException: Not a valid protocol version: This is not a HTTP port`

Looks like you're trying to use an HTTP client to talk to a non-HTTP service.

**Comment by sjq597** [comment]
but i just click the run button on the page

2017-03-02 12:00 GMT+08:00 Pat Patterson <notifications@github.com>:

**Comment by metadaddy** [comment]
OK - I see what's happening. We updated the Elasticsearch destination to use the HTTP protocol on port 9200, but the tutorial still references the old destination, which uses 9300. Change the port to 9200 and it should work. I'll fix the tutorial. Thanks for reporting this!

**Comment by sjq597** [comment]
@metadaddy thanks,it works now
