### ISSUE TITLE
does the JDBCQueryConsumer support hive JDBC?

### ISSUE THREAD

**Issue by littlebear-xbz** [streamsets/tutorials#64]
does the JDBCQueryConsumer support hive JDBC?
![image](https://user-images.githubusercontent.com/13586820/34316338-ea510ffc-e7cd-11e7-87e5-90488717da44.png)

com.streamsets.pipeline.api.StageException: JDBC_06 - Failed to initialize connection pool: com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: Method not supported
	at com.streamsets.pipeline.lib.jdbc.JdbcUtil.createDataSourceForRead(JdbcUtil.java:774)
	at com.streamsets.pipeline.stage.origin.jdbc.JdbcSource.init(JdbcSource.java:216)
	at com.streamsets.pipeline.api.base.BaseStage.init(BaseStage.java:48)
	at com.streamsets.pipeline.configurablestage.DStage.init(DStage.java:36)
	at com.streamsets.datacollector.runner.StageRuntime.init(StageRuntime.java:159)
	at com.streamsets.datacollector.runner.StagePipe.init(StagePipe.java:101)
	at com.streamsets.datacollector.runner.StagePipe.init(StagePipe.java:49)
	at com.streamsets.datacollector.runner.Pipeline.initPipe(Pipeline.java:382)
	at com.streamsets.datacollector.runner.Pipeline.init(Pipeline.java:295)
	at com.streamsets.datacollector.runner.preview.PreviewPipeline.run(PreviewPipeline.java:49)
	at com.streamsets.datacollector.execution.preview.sync.SyncPreviewer.start(SyncPreviewer.java:206)
	at com.streamsets.datacollector.execution.preview.async.AsyncPreviewer.lambda$start$0(AsyncPreviewer.java:94)
	at com.streamsets.pipeline.lib.executor.SafeScheduledExecutorService$SafeCallable.lambda$call$0(SafeScheduledExecutorService.java:249)
	at com.streamsets.datacollector.security.GroupsInScope.execute(GroupsInScope.java:33)
	at com.streamsets.pipeline.lib.executor.SafeScheduledExecutorService$SafeCallable.call(SafeScheduledExecutorService.java:245)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: Method not supported
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:581)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:152)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73)
	at com.streamsets.pipeline.lib.jdbc.JdbcUtil.createDataSourceForRead(JdbcUtil.java:767)
	... 20 more
Caused by: java.sql.SQLException: Method not supported
	at org.apache.hive.jdbc.HiveConnection.setReadOnly(HiveConnection.java:1198)
	at com.zaxxer.hikari.pool.PoolElf.setupConnection(PoolElf.java:184)
	at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:497)
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565)
	... 23 more

**Comment by xfg0218** [comment]
JDBC_00 - Cannot connect to specified database: com.streamsets.pipeline.api.StageException: JDBC_06 - Failed to initialize connection pool: com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: Method not supported

**Comment by metadaddy** [comment]
This is a problem with the Hive 1.x JDBC Driver - it does not correctly implement JDBC - see https://issues.apache.org/jira/browse/HIVE-11501
